name: Tensorflow
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.1
      - astunparse==1.6.3
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - imbalanced-learn==0.14.1
      - ipykernel==7.1.0
      - ipython==8.38.0
      - jedi==0.19.2
      - joblib==1.5.3
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - nest-asyncio==1.6.0
      - numpy==2.2.6
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pillow==12.1.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.4
      - psutil==7.2.1
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - requests==2.32.5
      - rich==14.2.0
      - scikeras==0.13.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sklearn-compat==0.1.5
      - stack-data==0.6.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - tornado==6.5.4
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - wcwidth==0.2.14
      - werkzeug==3.1.5
      - wrapt==2.0.1
