name: Prophet
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - asttokens=3.0.1
  - binutils_impl_win-64=2.45
  - binutils_win-64=2.45
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cmdstan=2.37.0
  - cmdstanpy=1.3.0
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - convertdate=2.4.0
  - cycler=0.12.1
  - debugpy=1.8.19
  - decorator=5.2.1
  - double-conversion=3.4.0
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freetype=2.14.1
  - gcc_impl_win-64=14.3.0
  - gcc_win-64=14.3.0
  - gendef=v12.0.0.r1.ggdc42231f0
  - graphite2=1.3.14
  - gxx_impl_win-64=14.3.0
  - gxx_win-64=14.3.0
  - harfbuzz=12.3.0
  - holidays=0.88
  - icu=78.2
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - ld_impl_win-64=2.45
  - lerc=4.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.8
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_win-64=14.3.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libhwloc=2.12.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libpng=1.6.54
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-devel_win-64=14.3.0
  - libtiff=4.7.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - m2-bash=5.2.037.2
  - m2-conda-epoch=20250515
  - m2-coreutils=8.32.5
  - m2-filesystem=2025.02.23.1
  - m2-gcc-libs=13.3.0.1
  - m2-gmp=6.3.0.1
  - m2-libiconv=1.18.1
  - m2-libintl=0.22.5.1
  - m2-make=4.4.1.2
  - m2-msys2-runtime=3.6.1.4
  - m2-sed=4.9.1
  - m2w64-sysroot_win-64=12.0.0.r4.gg4f2fc60ca
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mingw-w64-ucrt-x86_64-crt-git=12.0.0.r4.gg4f2fc60ca
  - mingw-w64-ucrt-x86_64-headers-git=12.0.0.r4.gg4f2fc60ca
  - mingw-w64-ucrt-x86_64-windows-default-manifest=6.4
  - mingw-w64-ucrt-x86_64-winpthreads-git=12.0.0.r4.gg4f2fc60ca
  - mkl=2025.3.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numpy=2.2.6
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.47
  - pickleshare=0.7.5
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - prophet=1.2.1
  - psutil=7.2.1
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pymeeus=0.5.12
  - pyparsing=3.3.1
  - pyside6=6.10.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.10.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - stanio=0.5.1
  - statsmodels=0.14.6
  - tbb=2022.3.0
  - tk=8.6.13
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - unicodedata2=17.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - et-xmlfile==2.0.0
      - joblib==1.5.3
      - narwhals==2.15.0
      - openpyxl==3.1.5
      - plotly==6.5.2
      - scikit-learn==1.7.2
      - threadpoolctl==3.6.0

