name: bayes_lgbm
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - arviz=0.23.0
  - asttokens=3.0.1
  - binutils_impl_win-64=2.45
  - binutils_win-64=2.45
  - blas=2.305
  - blas-devel=3.11.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.2.4
  - cairo=1.18.4
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - cons=0.4.7
  - contourpy=1.3.3
  - cycler=0.12.1
  - debugpy=1.8.19
  - decorator=5.2.1
  - etuples=0.3.10
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freeglut=3.8.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc=14.3.0
  - gcc_impl_win-64=14.3.0
  - gcc_win-64=14.3.0
  - gendef=v12.0.0.r1.ggdc42231f0
  - getopt-win32=0.1
  - graphite2=1.3.14
  - graphviz=13.1.2
  - gts=0.7.6
  - gxx=14.3.0
  - gxx_impl_win-64=14.3.0
  - gxx_win-64=14.3.0
  - h5netcdf=1.7.3
  - h5py=3.15.1
  - harfbuzz=12.3.0
  - hdf5=1.14.6
  - icu=73.2
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.3
  - jpeg=9e
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_win-64=2.45
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libboost=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=14.0.6
  - libcurl=8.18.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_win-64=14.3.0
  - libgd=2.3.3
  - libglib=2.84.4
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkrb5=1.21.3
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblightgbm=4.6.0
  - libpng=1.6.54
  - libpq=17.6
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_win-64=14.3.0
  - libtiff=4.7.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - llvm-openmp=21.1.8
  - logical-unification=0.4.7
  - m2-conda-epoch=20250515
  - m2w64-sysroot_win-64=12.0.0.r4.gg4f2fc60ca
  - markdown-it-py=4.0.0
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - mingw-w64-ucrt-x86_64-crt-git=12.0.0.r4.gg4f2fc60ca
  - mingw-w64-ucrt-x86_64-headers-git=12.0.0.r4.gg4f2fc60ca
  - mingw-w64-ucrt-x86_64-windows-default-manifest=6.4
  - mingw-w64-ucrt-x86_64-winpthreads-git=12.0.0.r4.gg4f2fc60ca
  - minikanren=1.0.5
  - minizip=4.0.6
  - mkl=2025.3.0
  - mkl-devel=2025.3.0
  - mkl-include=2025.3.0
  - mkl-service=2.6.1
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numpy=2.4.1
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.46
  - pillow=11.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pymc=5.26.1
  - pymc-base=5.26.1
  - pyparsing=3.3.1
  - pyside6=6.7.3
  - pytensor=2.35.1
  - pytensor-base=2.35.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-graphviz=0.21
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.3
  - qtwebsockets=6.7.3
  - rich=14.2.0
  - scikit-learn=1.8.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - toolz=1.1.0
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=17.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xarray=2025.12.0
  - xarray-einstats=0.9.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - scipy==1.17.0